#!/usr/bin/env python3
"""Generate a basic interactive HTML report from a PX4 ULog file."""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Optional

try:
    from bs4 import BeautifulSoup
except ImportError as exc:  # pragma: no cover
    raise SystemExit("Missing dependency: beautifulsoup4") from exc

try:
    import plotly.graph_objects as go
except ImportError as exc:  # pragma: no cover
    raise SystemExit("Missing dependency: plotly") from exc

try:
    from pyulog import ULog
except ImportError as exc:  # pragma: no cover
    raise SystemExit("Missing dependency: pyulog") from exc


def _load_vehicle_altitude(log: ULog) -> Optional[tuple[list[float], list[float]]]:
    """Extract timestamp (s) and altitude (m) from vehicle_local_position."""
    for dataset in log.data_list:
        if dataset.name != "vehicle_local_position":
            continue
        data = dataset.data
        timestamps = data.get("timestamp")
        z_values = data.get("z")
        if timestamps is None or z_values is None or len(timestamps) == 0:
            continue
        t0 = timestamps[0]
        time_axis = [(ts - t0) / 1e6 for ts in timestamps]
        altitude = [-z for z in z_values]  # NED: altitude is negative z
        return time_axis, altitude
    return None


def _build_plot(time_axis: list[float], altitude: list[float]) -> str:
    figure = go.Figure()
    figure.add_trace(
        go.Scatter(x=time_axis, y=altitude, mode="lines", name="Altitude (m)")
    )
    figure.update_layout(
        title="Vehicle Altitude",
        xaxis_title="Time (s)",
        yaxis_title="Altitude (m)",
        template="plotly_white",
    )
    return figure.to_html(full_html=False, include_plotlyjs="cdn")


def _render_html(title: str, body_fragment: str, summary: dict[str, float]) -> str:
    soup = BeautifulSoup("<html><head></head><body></body></html>", "html.parser")
    head = soup.head
    body = soup.body

    head.append(soup.new_tag("meta", charset="utf-8"))
    head.append(soup.new_tag("title"))
    head.title.string = title

    header = soup.new_tag("header")
    header.string = title
    body.append(header)

    summary_section = soup.new_tag("section")
    summary_section.append(soup.new_tag("h2"))
    summary_section.h2.string = "Quick Metrics"
    metrics_list = soup.new_tag("ul")
    for key, value in summary.items():
        item = soup.new_tag("li")
        item.string = f"{key}: {value:.2f}"
        metrics_list.append(item)
    summary_section.append(metrics_list)
    body.append(summary_section)

    plot_section = soup.new_tag("section")
    plot_section.append(soup.new_tag("h2"))
    plot_section.h2.string = "Altitude Profile"
    plot_container = BeautifulSoup(body_fragment, "html.parser")
    plot_section.append(plot_container)
    body.append(plot_section)

    footer = soup.new_tag("footer")
    footer.string = "Generated by generate_flight_report.py"
    body.append(footer)

    return str(soup)


def generate_report(ulog_path: Path, output_path: Path, summary_path: Optional[Path]) -> None:
    log = ULog(str(ulog_path))
    altitude_data = _load_vehicle_altitude(log)
    if altitude_data is None:
        raise SystemExit("vehicle_local_position topic not found in log")
    time_axis, altitude = altitude_data

    summary = {
        "Max Altitude (m)": max(altitude),
        "Min Altitude (m)": min(altitude),
        "Flight Duration (s)": time_axis[-1] if time_axis else 0.0,
    }
    if summary_path and summary_path.exists():
        try:
            with summary_path.open("r", encoding="utf-8") as handle:
                extra_summary = json.load(handle)
        except (json.JSONDecodeError, OSError):
            extra_summary = {}
        for key in ("elapsed_s", "target_altitude_m", "achieved_altitude_m"):
            if isinstance(extra_summary.get(key), (int, float)):
                label = key.replace("_", " ").title()
                summary[label] = float(extra_summary[key])

    plot_fragment = _build_plot(time_axis, altitude)
    html = _render_html("PX4 Flight Report", plot_fragment, summary)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    with output_path.open("w", encoding="utf-8") as handle:
        handle.write(html)


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("ulog", type=Path, help="Path to PX4 ULog file")
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("artifacts/flight_report.html"),
        help="Output HTML report",
    )
    parser.add_argument(
        "--summary",
        type=Path,
        default=Path("artifacts/takeoff_land_summary.json"),
        help="Optional JSON summary produced by scenarios",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv or sys.argv[1:])
    try:
        generate_report(args.ulog, args.output, args.summary)
    except Exception as exc:  # pragma: no cover
        print(f"Error: {exc}", file=sys.stderr)
        return 1
    print(f"Report written to {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
